#artemis网关服务器ip
artemis.host: 14.29.128.28
#秘钥appkey
artemis.appKey: 21453073
#秘钥appSecret
artemis.appSecret: Mj7Qx2hQD7v6Pt1sARF7
#车辆识别卡口id
vehicleData.crossingId: 2
#车辆识别时间（单位：ms）
vehicleData.recognizeTime: 4000