server:
  #访问端口
  port: 7001

#切换配置文件
spring:
  application:
    name: mock
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.15.23
        metadata:
          user:
            name: nacos
            password: nacos
          management:
            context-path: /actuator